from .academy_3_vs_1_with_keeper import Academy_3_vs_1_with_Keeper
from .academy_counterattack_hard import Academy_Counterattack_Hard
from .academy_run_pass_and_shoot_with_keeper import Academy_Run_Pass_and_Shoot_with_Keeper
from .five_vs_five import Five_vs_Five
from .academy_counterattack_easy import Academy_Counterattack_Easy
